---
language: ruby
cache: bundler
bundler_args: --without development
script:
    - "bundle exec rake validate && bundle exec rake lint && bundle exec rake spec SPEC_OPTS='--format documentation'"
rvm:
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION="~> 3.5.1" STRICT_VARIABLES="yes" ORDERING="random"
  - PUPPET_VERSION="~> 3.8.4" STRICT_VARIABLES="yes" ORDERING="random"
  - PUPPET_VERSION="~> 4.3.1" STRICT_VARIABLES="yes" ORDERING="random"
notifications:
  email: false
